apiVersion: v1
kind: Namespace
metadata:
  name: search
  labels:
    env: prod
    team: search
    app.kubernetes.io/part-of: acme-platform
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: search-compute-quota
  namespace: search
  annotations:
    argocd.argoproj.io/tracking-id: search:v1/ResourceQuota:search/search-compute-quota
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 18Gi
    limits.cpu: "18"
    limits.memory: 48Gi
    pods: "40"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: search-defaults
  namespace: search
spec:
  limits:
    - type: Container
      default:
        cpu: 750m
        memory: 768Mi
      defaultRequest:
        cpu: 250m
        memory: 320Mi
      max:
        cpu: "2"
        memory: 4Gi
